FROM ubuntu:xenial
WORKDIR /opt/chimera/bin
RUN apt-get update && apt-get install -y \
    curl \
    && curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/webapp \
    --output webapp \
    && chmod +x webapp
ENV WEBAPP_PORT=80
EXPOSE ${WEBAPP_PORT}
# The data folder should be shared with the cliapp
ENV REDIS_HOST=redis-host
ENV REDIS_PORT=6379
RUN mkdir /var/log/chimera
ENTRYPOINT ["./webapp"]
