FROM ubuntu:xenial
RUN apt-get update && apt-get install -y \
    cron \
    curl \
    jq
WORKDIR /opt/chimera/bin
RUN curl https://devops-command-line-workshop.s3.eu-west-2.amazonaws.com/cliapp \
    --output cliapp \
    && chmod +x cliapp
COPY ./run.sh ./run.sh
RUN chmod +x ./run.sh
# The data is shared via Redis
ENV REDIS_HOST=redis-cache
ENV REDIS_PORT=6379
RUN mkdir /var/log/chimera \
    && touch /var/log/cron.log
ENTRYPOINT ["./run.sh"]
