version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-cache
    volumes:
      - redis-cache:/data
  cliapp:
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    ports:
      - 6379
    links:
      - redis
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
      - 6379
    links:
      - redis

volumes:
  redis-cache:
